"""
hunt.py — run one routine of the Map of Meaning.

    python -m meaning_map.hunt              # full lexica, default backend
    python -m meaning_map.hunt --max 40000  # cap lexicon size for a quick pass

Outputs (next to this package):
  * resonance_reservoir.jsonl   append-only journal (memory across routines)
  * MAP_OF_MEANING.md           human-readable frontier report for this run
"""

from __future__ import annotations

import argparse
import os
import time
from collections import Counter
from typing import List

from . import journal, resonance
from .lexicon_index import default_data_dir, load_lexicon
from .resonance import Resonance
from .semantic_oracle import SeedDictOracle

HERE = os.path.dirname(os.path.abspath(__file__))
RESERVOIR = os.path.join(HERE, "resonance_reservoir.jsonl")
REPORT = os.path.join(HERE, "MAP_OF_MEANING.md")

TIER_ORDER = ["GOLD", "SILVER", "BRONZE", "FRONTIER"]


def run(max_entries: int | None, data_dir: str) -> None:
    run_id = time.strftime("%Y%m%dT%H%M%S")
    print(f"[meaning_map] routine {run_id}")

    fr_lex = load_lexicon(os.path.join(data_dir, "lexique.tsv"), "fr",
                          max_entries=max_entries)
    en_lex = load_lexicon(os.path.join(data_dir, "lexique_en.tsv"), "en",
                          max_entries=max_entries)
    print(f"[meaning_map] fr={fr_lex.size()} en={en_lex.size()} words")

    oracle = SeedDictOracle()
    found = resonance.dedupe(
        resonance.concept_hunt(en_lex, fr_lex, oracle)
        + resonance.sound_hunt(en_lex, fr_lex, oracle)
    )
    found.sort(key=lambda r: (r.phon_sim + r.sem_score), reverse=True)

    seen = journal.load_seen(RESERVOIR)
    fresh = [r for r in found if r.key() not in seen]
    journal.append(RESERVOIR, (resonance.to_record(r, run_id) for r in fresh))

    print(f"[meaning_map] {len(found)} resonances ({len(fresh)} new this routine)")
    write_report(found, fresh, run_id, fr_lex.size(), en_lex.size())
    print(f"[meaning_map] wrote {REPORT}")


def _tier_section(title: str, items: List[Resonance], limit: int = 40) -> str:
    if not items:
        return f"### {title}\n\n_none this routine_\n"
    lines = [f"### {title}  ({len(items)})", "",
             "| EN | /IPA/ | FR | /IPA/ | sound | meaning | basis |",
             "|----|-------|----|-------|------:|--------:|-------|"]
    for r in items[:limit]:
        lines.append(
            f"| {r.en_word} | /{r.en_ipa}/ | {r.fr_word} | /{r.fr_ipa}/ "
            f"| {r.phon_sim:.2f} | {r.sem_score:.2f} | {r.basis} |"
        )
    if len(items) > limit:
        lines.append(f"\n_…and {len(items) - limit} more (see reservoir)_")
    return "\n".join(lines) + "\n"


def write_report(found: List[Resonance], fresh: List[Resonance], run_id: str,
                 fr_n: int, en_n: int) -> None:
    by_tier = {t: [r for r in found if r.tier == t] for t in TIER_ORDER}
    counts = Counter(r.tier for r in found)
    fresh_counts = Counter(r.tier for r in fresh)

    out = [
        "# The Map of Meaning — EN ↔ FR Resonances",
        "",
        f"_Routine `{run_id}` · {journal.now()} · lexica: en={en_n}, fr={fr_n} words_",
        "",
        "Where **sound** (cross-lingual homophony) and **meaning** (translation, "
        "or one synonym hop) converge on the same pair of words, a *resonance* "
        "rings. This is the living frontier; the reservoir remembers every "
        "verdict so each routine whittles toward the perfect matches.",
        "",
        "## Tally",
        "",
        "| tier | total | new this routine |",
        "|------|------:|-----------------:|",
    ]
    for t in TIER_ORDER:
        out.append(f"| {t} | {counts.get(t, 0)} | {fresh_counts.get(t, 0)} |")
    out += [
        "",
        "- **GOLD** — the word both *sounds like* and *means* its counterpart.",
        "- **SILVER / BRONZE** — strong sound + confirmed meaning (incl. synonym chains).",
        "- **FRONTIER** — strong sound, meaning not yet established: the hunting ground.",
        "",
        "## Tiers",
        "",
        _tier_section("🥇 GOLD — sound and meaning converge", by_tier["GOLD"]),
        _tier_section("🥈 SILVER", by_tier["SILVER"]),
        _tier_section("🥉 BRONZE", by_tier["BRONZE"]),
        _tier_section("🛰️ FRONTIER — sound-twins awaiting a meaning", by_tier["FRONTIER"]),
        "---",
        "",
        "_Generated by `python -m meaning_map.hunt`. Memory: "
        "`resonance_reservoir.jsonl`. Next steps: `ROUTINE.md`._",
    ]
    with open(REPORT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))


def main() -> None:
    ap = argparse.ArgumentParser(description="Run one Map-of-Meaning routine.")
    ap.add_argument("--max", type=int, default=None,
                    help="cap entries loaded per lexicon (speed/dev)")
    ap.add_argument("--data-dir", default=default_data_dir())
    args = ap.parse_args()
    run(args.max, args.data_dir)


if __name__ == "__main__":
    main()
