#!/usr/bin/env python3
"""
map_of_meaning_cli.py
~~~~~~~~~~~~~~~~~~~~~~

Command line front-end to the Map of Meaning engine.

Examples
--------
    # Find FR words that sound like AND mean an English word
    python map_of_meaning_cli.py render --word envy

    # The headline hunt: FR words that sound like their own English meaning
    python map_of_meaning_cli.py golden --min-sim 0.85 --hide-cognates --limit 40

    # Sound-only neighbours of an English word in the French lexicon
    python map_of_meaning_cli.py homophones --word night

    # Translation-bridge synonyms of an English word
    python map_of_meaning_cli.py synonyms --word love

    # Regenerate the markdown + TSV report under artifacts/
    python map_of_meaning_cli.py report
"""

from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from src.map_of_meaning import MapOfMeaning  # noqa: E402

ARTIFACTS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts")


def _engine() -> MapOfMeaning:
    return MapOfMeaning()


def cmd_golden(args: argparse.Namespace) -> None:
    eng = _engine()
    matches = eng.golden_matches(min_sim=args.min_sim,
                                 include_cognates=not args.hide_cognates)
    print(f"# {len(matches)} golden matches (min_sim={args.min_sim}, "
          f"{'no cognates' if args.hide_cognates else 'incl. cognates'})\n")
    for m in matches[: args.limit]:
        tag = "cognate" if m.cognate else "GEM"
        print(f"{m.sound:.2f}  {m.fr:<16} /{m.fr_ipa}/  ⇄  {m.en:<16} "
              f"/{m.en_ipa}/   [{tag}]")


def cmd_render(args: argparse.Namespace) -> None:
    eng = _engine()
    rs = eng.meaningful_renderings(args.word, top_k=args.limit)
    if not rs:
        print(f"(no French renderings found for {args.word!r} — "
              f"is it in lexique_en.tsv?)")
        return
    print(f"# French renderings of {args.word!r} "
          f"(sound × meaning)\n")
    for r in rs:
        gl = ", ".join(r.glosses[:4]) or "—"
        print(f"score={r.score:.2f}  sound={r.sound:.2f}  meaning={r.meaning:.2f} "
              f"[{r.via}]  {r.fr} /{r.fr_ipa}/  ⟶ {gl}")


def cmd_homophones(args: argparse.Namespace) -> None:
    eng = _engine()
    hs = eng.homophones_of(args.word, top_k=args.limit, min_sim=args.min_sim)
    print(f"# French sound-alikes of {args.word!r}\n")
    for fr, ipa, s in hs:
        print(f"{s:.2f}  {fr} /{ipa}/")


def cmd_synonyms(args: argparse.Namespace) -> None:
    eng = _engine()
    syns = sorted(eng.synonyms_en(args.word))
    print(f"# translation-bridge synonyms of {args.word!r}: "
          f"{', '.join(syns) if syns else '(none)'}")


def cmd_report(args: argparse.Namespace) -> None:
    eng = _engine()
    os.makedirs(ARTIFACTS, exist_ok=True)
    stats = eng.stats()
    golden = eng.golden_matches(min_sim=0.6, include_cognates=True)
    gems = [m for m in golden if not m.cognate]

    # TSV of every golden match for downstream tooling.
    tsv = os.path.join(ARTIFACTS, "golden_matches.tsv")
    with open(tsv, "w", encoding="utf-8") as fh:
        fh.write("sound\tfr\tfr_ipa\ten\ten_ipa\tcognate\n")
        for m in golden:
            fh.write(f"{m.sound}\t{m.fr}\t{m.fr_ipa}\t{m.en}\t{m.en_ipa}\t"
                     f"{int(m.cognate)}\n")

    # Human-readable markdown report.
    md = os.path.join(ARTIFACTS, "map_of_meaning_report.md")
    with open(md, "w", encoding="utf-8") as fh:
        fh.write("# Map of Meaning — Generated Report\n\n")
        fh.write("Auto-generated by `map_of_meaning_cli.py report`.\n\n")
        fh.write("## Corpus\n\n")
        for k, v in stats.items():
            fh.write(f"- **{k}**: {v:,}\n")
        fh.write(f"\n## Golden matches (sound ⇄ meaning)\n\n")
        fh.write(f"- total scored ≥0.60: **{len(golden):,}**\n")
        fh.write(f"- non-cognate gems: **{len(gems):,}**\n\n")
        fh.write("### Top non-cognate gems "
                 "(French word that sounds like an *unrelated-spelling* English meaning)\n\n")
        fh.write("| sound | French | IPA | means (EN) | IPA |\n|---|---|---|---|---|\n")
        for m in gems[:60]:
            fh.write(f"| {m.sound:.2f} | {m.fr} | /{m.fr_ipa}/ | "
                     f"{m.en} | /{m.en_ipa}/ |\n")
        fh.write("\n### Top cognate confirmations (sanity check)\n\n")
        fh.write("| sound | French | English |\n|---|---|---|\n")
        for m in [g for g in golden if g.cognate][:25]:
            fh.write(f"| {m.sound:.2f} | {m.fr} | {m.en} |\n")
    print(f"wrote {tsv}\nwrote {md}")
    print(json.dumps(stats, indent=2))
    print(f"golden total: {len(golden)}  gems: {len(gems)}")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Map of Meaning CLI")
    sub = p.add_subparsers(dest="cmd", required=True)

    g = sub.add_parser("golden", help="FR words that sound like their own EN meaning")
    g.add_argument("--min-sim", type=float, default=0.7)
    g.add_argument("--hide-cognates", action="store_true")
    g.add_argument("--limit", type=int, default=40)
    g.set_defaults(func=cmd_golden)

    r = sub.add_parser("render", help="FR words that sound like AND mean an EN word")
    r.add_argument("--word", required=True)
    r.add_argument("--limit", type=int, default=15)
    r.set_defaults(func=cmd_render)

    h = sub.add_parser("homophones", help="FR sound-alikes of an EN word")
    h.add_argument("--word", required=True)
    h.add_argument("--min-sim", type=float, default=0.6)
    h.add_argument("--limit", type=int, default=20)
    h.set_defaults(func=cmd_homophones)

    s = sub.add_parser("synonyms", help="translation-bridge synonyms of an EN word")
    s.add_argument("--word", required=True)
    s.set_defaults(func=cmd_synonyms)

    rep = sub.add_parser("report", help="regenerate artifacts/ report + TSV")
    rep.set_defaults(func=cmd_report)

    args = p.parse_args(argv)
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
